@TodoList_HostAddress = https://localhost:7129


POST {{TodoList_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}
###

GET {{TodoList_HostAddress}}/todoitems

###

GET {{TodoList_HostAddress}}/todoitems/3

###

PUT {{TodoList_HostAddress}}/todoitems/3
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete" : false
}
###

DELETE {{TodoList_HostAddress}}/todoitems/3

###
